# -*- coding: utf-8 -*-
"""Chat_assistance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1njzYskxB9HJWuBvrLWdxI0m0VUhw2CEq
"""

pip install openai

pip install gradio

import openai
import gradio

openai.api_key = "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"

messages = [{"role": "system", "content": "You are a financial experts that specializes in real estate investment and negotiation"}]

def CustomChatGPT(user_input):
    messages.append({"role": "user", "content": user_input})
    response = openai.ChatCompletion.create(
        model = "gpt-3.5-turbo",
        messages = messages
    )
    ChatGPT_reply = response["choices"][0]["message"]["content"]
    messages.append({"role": "assistant", "content": ChatGPT_reply})
    return ChatGPT_reply

demo = gradio.Interface(fn=CustomChatGPT, inputs = "text", outputs = "text", title = "Your Assistant")

demo.launch(share=True)